name: Gatsby Build

on:
  push:
    branches:
      - '!main'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Build
        run: |
          npm ci --legacy-peer-deps
          npm run build